name: blog-archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run
      env:
        API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        OWNER: ${{ secrets.OWNER }}
        REPO: ${{ secrets.REPO }}
      run: cargo run
    - name: commit
      run: |
        sudo git config --global user.email ${{ secrets.COMMIT_EMAIL }}
        sudo git config --global user.name ${{ secrets.COMMIT_USER_NAME }}
        git pull
        git add .
        git commit -m 'auto update blog'
        git push
      
  
