name: blog-archive

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  blog-archive:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run
      env:
        API_GITHUB_TOKEN: ${{ inputs.api-github-token }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
      run: cargo run
    - name: commit
      run: |
        sudo git config user.email ${{ inputs.git-user-email }}
        sudo git config user.name ${{ inputs.git-user-name }}
        git config user.email
        git config user.name
        git pull
        git add .
        git commit -m 'auto update blog'
        git push
      
  
